site_name: Boo
site_description: integrates llms with multimodal support for text, image, audio, and file analysis.
site_url: https://is-leeroy-jenkins.github.io/boo
repo_url: https://github.com/is-leeroy-jenkins/boo
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.action.edit
    - search.suggest
    - search.highlight
  palette:
    - scheme: default

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_signature: true
            show_source: true
            separate_signature: true
            heading_level: 2
  - section-index

markdown_extensions:
  - admonition
  - def_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - How-to:
      - Summarize a document: how-to/summarize-a-document.md
      - Search vector stores: how-to/search-vector-stores.md
      - Analyze an image: how-to/analyze-an-image.md
      - Stream TTS to file: how-to/stream-tts-to-file.md
      - Web Search: how-to/web-search.md
      - File Search: how-to/file-search.md
  - API Reference:
      - boo: reference/boo.md
      - boogr: reference/boogr.md
      - mathy: reference/mathy.md
